[package]
name = "wasm"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
wasm-bindgen = "0.2"
serde-wasm-bindgen = "0.4"
once_cell = "1.8"
serde_json = "1.0"
crypto_utils = { path = "../crypto_utils" }
